name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5

  check-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm check-deps

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm coverage

  build:
    needs: [commitlint, check-deps, lint, test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - name: save build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  release-please:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: "@jcartledge/${{github.event.repository}}"

      - uses: actions/checkout@v3
        if: ${{steps.release.outputs.release_created}}

      - uses: pnpm/action-setup@v2
        if: ${{steps.release.outputs.release_created}}

      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          registry-url: "https://registry.npmjs.org"
        if: ${{steps.release.outputs.release_created}}

      - name: retrieve build artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
        if: ${{steps.release.outputs.release_created}}

      - run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{steps.release.outputs.release_created}}

      - name: Build docs
        run: pnpm docs
        if: ${{steps.release.outputs.release_created}}

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
        if: ${{steps.release.outputs.release_created}}
